{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "argocd-appset-secret-plugin.fullname" . }}-clusterrolebinding
  labels:
    {{- include "argocd-appset-secret-plugin.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd-appset-secret-plugin.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  {{- if .Values.rbac.useExistingClusterRole }}
  name: {{ .Values.rbac.useExistingClusterRole }}
  {{- else }}
  name: {{ include "argocd-appset-secret-plugin.fullname" . }}-clusterrole
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
