name: nightly and on.push docker builds

on:
  # to trigger manually if we really need it
  workflow_dispatch:

  push:
    paths:
      - docker/**
      - "!docker/README.md"
    tags:
      - "v*.*.*"

  schedule:
    # * is a special character in YAML so you have to quote this string
    # triggers every day at 00:00 UTC (midnight)
    - cron:  '0 0 * * *'

jobs:
  docker-amd64:
    environment: 'docker'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/push - prereqs only
        uses: docker/build-push-action@v6
        with:
          push: true
          # build from docker/ directory
          context: docker
          platforms: |
            linux/amd64
            linux/arm64
          tags: | 
            jessebot/argocd-appset-secret-plugin:latest
            jessebot/argocd-appset-secret-plugin:${{ github.ref_name }}
